a.out: 5.1_CLinkedListMain.o 5.1_CLinkedList.o
	gcc -o a.out 5.1_CLinkedListMain.o 5.1_CLinkedList.o

5.1_CLinkedListMain.o: 5.1_CLinkedListMain.c
	gcc -c -o 5.1_CLinkedListMain.o 5.1_CLinkedListMain.c

5.1_CLinkedList.o: 5.1_CLinkedList.c
	gcc -c -o 5.1_CLinkedList.o 5.1_CLinkedList.c

clean:
	rm *.o a.out
