a.out: 4.2_DLinkedListSortMain.o 4.2_DLinkedList.o
	gcc -o a.out 4.2_DLinkedListSortMain.o 4.2_DLinkedList.o

4.2_DLinkedListSortMain.o: 4.2_DLinkedListSortMain.c
	gcc -c -o 4.2_DLinkedListSortMain.o 4.2_DLinkedListSortMain.c

4.2_DLinkedList.o: 4.2_DLinkedList.c
	gcc -c -o 4.2_DLinkedList.o 4.2_DLinkedList.c

clean:
	rm *.o a.out
