a.out: 7.3_ListBaseQueueMain.o 7.3_ListBaseQueue.o
	gcc -o a.out 7.3_ListBaseQueueMain.o 7.3_ListBaseQueue.o

7.3_ListBaseQueueMain.o: 7.3_ListBaseQueueMain.c
	gcc -c -o 7.3_ListBaseQueueMain.o 7.3_ListBaseQueueMain.c

7.3_ListBaseQueue.o: 7.3_ListBaseQueue.c
	gcc -c -o 7.3_ListBaseQueue.o 7.3_ListBaseQueue.c

clean:
	rm *.o a.out
