a.out: 3.2_ListMain.o 3.2_ArrayList.o
	gcc -o a.out 3.2_ListMain.o 3.2_ArrayList.o

3.2_ListMain.o: 3.2_ListMain.c
	gcc -c -o 3.2_ListMain.o 3.2_ListMain.c

3.2_ArrayList.o: 3.2_ArrayList.c
	gcc -c -o 3.2_ArrayList.o 3.2_ArrayList.c

clean:
	rm *.o a.out
