a.out: 4.2_DLinkedListMain.o 4.2_DLinkedList.o
	gcc -o a.out 4.2_DLinkedListMain.o 4.2_DLinkedList.o

4.2_DLinkedListMain.o: 4.2_DLinkedListMain.c
	gcc -c -o 4.2_DLinkedListMain.o 4.2_DLinkedListMain.c

4.2_DLinkedList.o: 4.2_DLinkedList.c
	gcc -c -o 4.2_DLinkedList.o 4.2_DLinkedList.c

clean:
	rm *.o a.out
