a.out: 6.2_ArrayBaseStackMain.o 6.2_ArrayBaseStack.o
	gcc -o a.out 6.2_ArrayBaseStackMain.o 6.2_ArrayBaseStack.o

6.2_ArrayBaseStackMain.o: 6.2_ArrayBaseStackMain.c
	gcc -c -o 6.2_ArrayBaseStackMain.o 6.2_ArrayBaseStackMain.c

6.2_ArrayBaseStack.o: 6.2_ArrayBaseStack.c
	gcc -c -o 6.2_ArrayBaseStack.o 6.2_ArrayBaseStack.c

clean:
	rm *.o a.out
