a.out: 6.3_ListBaseStackMain.o 6.3_ListBaseStack.o
	gcc -o a.out 6.3_ListBaseStackMain.o 6.3_ListBaseStack.o

6.3_ListBaseStackMain.o: 6.3_ListBaseStackMain.c
	gcc -c -o 6.3_ListBaseStackMain.o 6.3_ListBaseStackMain.c

6.3_ListBaseStack.o: 6.3_ListBaseStack.c
	gcc -c -o 6.3_ListBaseStack.o 6.3_ListBaseStack.c

clean:
	rm *.o a.out
