a.out: 7.4_HamburgerSim.o 7.4_CircularQueue.o
	gcc -o a.out 7.4_HamburgerSim.o 7.4_CircularQueue.o

7.4_HamburgerSim.o: 7.4_HamburgerSim.c
	gcc -c -o 7.4_HamburgerSim.o 7.4_HamburgerSim.c

7.4_CircularQueue.o: 7.4_CircularQueue.c
	gcc -c -o 7.4_CircularQueue.o 7.4_CircularQueue.c

clean:
	rm *.o a.out
