a.out: 7.5_DequeMain.o 7.5_Deque.o
	gcc -o a.out 7.5_DequeMain.o 7.5_Deque.o

7.5_DequeMain.o: 7.5_DequeMain.c
	gcc -c -o 7.5_DequeMain.o 7.5_DequeMain.c

7.5_Deque.o: 7.5_Deque.c
	gcc -c -o 7.5_Deque.o 7.5_Deque.c

clean:
	rm *.o a.out
