a.out: 5.2_DBLinkedListMain.o 5.2_DBLinkedList.o
	gcc -o a.out 5.2_DBLinkedListMain.o 5.2_DBLinkedList.o

5.2_DBLinkedListMain.o: 5.2_DBLinkedListMain.c
	gcc -c -o 5.2_DBLinkedListMain.o 5.2_DBLinkedListMain.c

5.2_DBLinkedList.o: 5.2_DBLinkedList.c
	gcc -c -o 5.2_DBLinkedList.o 5.2_DBLinkedList.c

clean:
	rm *.o a.out
