a.out: 8.2_BinaryTreeMain.o 8.2_BinaryTree.o
	gcc -o a.out 8.2_BinaryTreeMain.o 8.2_BinaryTree.o

8.2_BinaryTreeMain.o: 8.2_BinaryTreeMain.c
	gcc -c -o 8.2_BinaryTreeMain.o 8.2_BinaryTreeMain.c

8.2_BinaryTree.o: 8.2_BinaryTree.c
	gcc -c -o 8.2_BinaryTree.o 8.2_BinaryTree.c

clean:
	rm *.o a.out
